config/routes.rb
Rails.application.routes.draw do  
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  resources :recipes

  root "recipes#index"

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	ratyrate_rateable 'visual_effects', 'original_score', 'director', 'custome_design'
	belongs_to :user
  	has_many :ingredients
  	has_many :directions
  	accepts_nested_attributes_for :ingredients,
  		reject_if: proc { |attributes| attributes['name'].blank? },
  			allow_destroy: true
 	accepts_nested_attributes_for :directions,
 		reject_if: proc { |attributes| attributes['step'].blank? },
  			allow_destroy: true
 	validates :title, :description, :image, presence: true
	has_attached_file :image, styles: { :medium => "400x400#", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :recipes
	ratyrate_rater
	attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy ]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@recipe = Recipe.all.order("created_at DESC")
	end

	def show 

	end

	def new
		@recipe = current_user.recipes.build
	end

	def create
		@recipe = current_user.recipes.build(recipe_params)

		if @recipe.save
			redirect_to @recipe, notice: "Successfully created new recipe"
		else
			render 'new'
		end
	end

	def edit
	end

	def update	
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe.destroy
		redirect_to root_path, notice: "Successfully deleted recipe"
	end

	private

	def recipe_params
		params.require(:recipe).permit(:title, :username, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
	end

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end


end

app/controllers/registration _controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
 	Any feedback is  appreciated! Alwan Mortada	
</footer>

app/views/layouts/_header.html.erb
<header>	
	<nav class="navbar navbar-default">
    	<div class="container">
	      	<div class="navbar-brand">
		        <%= link_to "Chicken Box", root_path %>
		    </div>
		      	<br>

		      	<% if user_signed_in? %>
		        	<ul class="nav navbar-nav navbar-right ">
			          	<li>
			            	<%= link_to "New Recipe", new_recipe_path, class: "btn btn-warning"%>
			          	</li>
			          	<li>
			           	 <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-warning" %>
			          	</li>
		       	 </ul>
		     	 <% else %>
		      	  	<button type="button"  class="btn btn btn-default navbar-btn pull-right" >
		          
		        	    <%= link_to "Sign Up", new_user_registration_path %>
		        	</button>

		        	<button type="button"  class="btn btn-default navbar-btn pull-right">
		        	    <%= link_to "Sign In", new_user_session_path %>
		        	</button>
		     	 <% end %>
	   	 	</div>
  	<ul class="nav navbar-nav">
  			<li>
				<a href="https://twitter.com/share" class="twitter-share-button" data-url="https://frie-away-chicken.herokuapp.com/" data-via="mortada_alwan" data-related="GA_ATX">Tweet</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
			</li>
			<li >		
				<button type="button" class="btn btn-warning" data-toggle="modal" data-target=".bs-example-modal-lg">About</button>
					<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  						<div class="modal-dialog modal-lg">
   						 <div class="modal-content" >
      						This app is inspired by my favorite fried chicken restaurant on South Congress Lucy's fired chicken. This app is fully functional.
      						Users can post a favorite fried chicken recipes, users can vote out of 5 stars what they think.
      						This app uses couple of gem such as 'devise' for authentication-sass' for style,simple_form, paperclip for images, cocoon for nested routes, ratyrate for rating ! I had lot of fun building this app hope you enjoy.
    					 </div>
  						</div>
					</div>
			</li>

			<li>
				<button type="button" class="btn btn-warning" data-toggle="modal" data-target=".bs-example-modal-sm">Contact me</button>
					<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
						<div class="modal-dialog modal-sm">
						 <!-- <div class="modal-content"> -->
						<a target="_blank" title="follow us on facebook" href="https://www.facebook.com/alwan.mortada"><img alt="follow us on facebook" src="https://c866088.ssl.cf3.rackcdn.com/assets/facebook30x30.png" border=0></a>

       					<a target="_blank" title="follow us on Twitter" href="https://twitter.com/mortada_alwan"><img alt="follow us on Twitter" src="https://c866088.ssl.cf3.rackcdn.com/assets/twiiter30x30.png" border=0></a>				

        				<a target="_blank" title="follow us on instagram" href="https://instagram.com/alwanmortada/"><img alt="follow us on instagram" src="https://c866088.ssl.cf3.rackcdn.com/assets/instagram30x30.png" border=0></a>				

        				<a target="_blank" title="follow us on wordpress" href="https://theegrasshopper.wordpress.com/"><img alt="follow us on instagram" src="https://s.w.org/about/images/logos/wordpress-logo-32-blue.png" border=0></a>					
  					</div>
			</li>
		</ul>
	</nav>
 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chicken Box</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
  
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert" %>
    <% end %>
    <%= yield %>
  </div>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/recipes/_direction_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :step, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove Step", f, class: "btn btn-default form-button" %>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: { multipart: true, class: "directUpload" } do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <p>
        <%= @recipe.errors.count %>
        Prevented this recipe froms saving
      </p>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel-body">
    <%= f.input :title, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { class: 'form-control' } %>
    
    <!--/assets/javascripts/application.js-->
    <div class="field">
  <%= f.label :image %><br>
  <%= f.file_field :image, input_html: { class: 'form-control' } %>
      </div>

      <!--/assets/javascripts/application.js  -->
    <div class="row">
      <div class="col-md-6">
        <h3>Ingredients</h3>
        <div id="ingredients">
          <%= f.simple_fields_for :ingredients do |ingredient| %>
            <%= render 'ingredient_fields', f: ingredient %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button" %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <h3>Directions</h3>
        <div id="directions">
          <%= f.simple_fields_for :directions do |direction| %>
            <%= render 'direction_fields', f: direction %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1> Edit Recipe</h1>

<%= render 'form' %>

<%= link_to "Back", root_path, class: "btn btn-default" %>
<%= link_to "Recipe", recipe_path, class: "btn btn-default" %>

app/views/recipes/index.html.erb
<% @recipe.each_slice(3) do |recipes| %>
  <div class="row">
    <% recipes.each do |recipe| %>
      <div class="col-md-4">
        <div class="recipe">
          <div class="image_wrapper">
            <%= link_to recipe do %>
              <%= image_tag recipe.image.url(:medium) %>
              
            <% end %>
          </div>
          <h2>
            <%= link_to recipe.title, recipe %>
          </h2>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe 
  <%= render 'form' %>
  <br/>
  <%= link_to "Back", root_path, class: "btn btn-default" %>
</h1>

app/views/recipes/show.html.erb
<%= image_tag @recipe.image.url(:medium, class:"recipe_image") %>

<div class="row">
  <div class="small-2 large-2 columns">
     <div class="container">
     <p> Rate this :
     <%= javascript_include_tag 'ratyrate.js.erb', "data-turbolinks-track" => false %>
    <%= imdb_style_rating_for @recipe, current_user, disable_after_rate: true, imdb_avg: true%>  
    </p> 
  </div>
  <br>

  <div class="small-2 large-4 columns">
   <div class="container">
   <% if current_user.id != @recipe.user.id %>
      Original Score: <%= rating_for @recipe, "original_score", disable_after_rate: true, imdb_avg: true, stars: 10 %>
      <%end%>
      <br>
     </div>
    </div>
  </div>
</div>
<h1><%= @recipe.title %></h1>
<P><%= @recipe.description %></P>
<p>Submitted by: <%= @recipe.user.username %></p>

<%= link_to "Back", root_path, class: "btn btn-default" %>
<% if current_user.id == @recipe.user.id %>
<%= link_to "edit", edit_recipe_path, class: "btn btn-default" %>
<%= link_to "Delete", recipe_path, method: :delete, data: {confirm:"Are you sure?"}, class: "btn btn-default" %>
<% end %>



<div class="main_content">
  <div class="row">
    <div class="col-md-6">
      <div id="ingredients">
        <h2>Ingredients</h2>
        <ul>
          <% @recipe.ingredients.each do |ingredient| %>
            <li>
              <%= ingredient.name %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      <div id="directions">
        <h2>Directions</h2>
        <ul>
          <% @recipe.directions.each do |direction| %>
            <li>
              <%= direction.step %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>